// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATPedPO8AABIvx5qnUEiDx_aEWwijOf0g',
    appId: '1:810256488887:web:07ca63e30a71b812c8b032',
    messagingSenderId: '810256488887',
    projectId: 'flutter-projects-79356',
    authDomain: 'flutter-projects-79356.firebaseapp.com',
    storageBucket: 'flutter-projects-79356.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANEhjh-LS6c4VPGUhX14vcIrOLZ3JifWM',
    appId: '1:810256488887:android:78183b30c66365fec8b032',
    messagingSenderId: '810256488887',
    projectId: 'flutter-projects-79356',
    storageBucket: 'flutter-projects-79356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBHqnOsZ-acUL8lGiuLsdhw4Wv9wM7Dos',
    appId: '1:810256488887:ios:f553e5e0d8781eb0c8b032',
    messagingSenderId: '810256488887',
    projectId: 'flutter-projects-79356',
    storageBucket: 'flutter-projects-79356.firebasestorage.app',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBHqnOsZ-acUL8lGiuLsdhw4Wv9wM7Dos',
    appId: '1:810256488887:ios:c8d7a8bb89842045c8b032',
    messagingSenderId: '810256488887',
    projectId: 'flutter-projects-79356',
    storageBucket: 'flutter-projects-79356.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATPedPO8AABIvx5qnUEiDx_aEWwijOf0g',
    appId: '1:810256488887:web:384e50dc91b8fb9dc8b032',
    messagingSenderId: '810256488887',
    projectId: 'flutter-projects-79356',
    authDomain: 'flutter-projects-79356.firebaseapp.com',
    storageBucket: 'flutter-projects-79356.firebasestorage.app',
  );
}
